title: Tieso
author: Andi Gavilanes M.
email: andigavilanes@protonmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Dataism - Information Security
  

# social links
twitter_username: hackapoyo # DO NOT include the @ character, or else the build will fail!
github_username:  andigavilanesmolina # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
